name: Default

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Dependencies setup
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run unit tests with coverage
        run: npm run test:cov
