name: Default

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Dependencies setup
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run linters
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test:cov

      - name: Run e2e tests
        run: npm run test:e2e
